Added coinbase tagging of UTXOS
bitcoinjs/indexd pull request #45
Opened 2019-02-07 21:01 UTC by chiguireitor

2019-02-07 23:51 UTC, junderw requested changes
Initial review. Request changes.

2019-02-07 23:51 UTC, junderw commented on indexes/txin.js
> +        vout = 0
iirc, coinbase inputs use 0xffffffff as vout.

2019-02-07 23:51 UTC, junderw commented on indexes/txo.js
> +console.log('*****', txo)
please remove

2019-02-08 04:48 UTC, chiguireitor commented on indexes/txo.js
> +console.log('*****', txo)
Doh!

2019-02-08 04:49 UTC, chiguireitor commented
Changes in, please review as this inhibits any mining node to use indexd correctly

2019-02-08 06:12 UTC, junderw submitted a review, later dismissed
please change vout, not txid. txid was fine as is. Thanks.

2019-02-08 06:12 UTC, junderw commented on indexes/txin.js
> +        vout = 0
This is what I meant.
```javascript
prevTxId = '0000000000000000000000000000000000000000000000000000000000000000'
vout = 0xffffffff
```

2019-02-08 13:04 UTC, chiguireitor commented
Corrections in, check it out plz

2019-03-14 05:13 UTC, chiguireitor commented
Hi, any progress on this? This is a breaking issue for regtest (which is a real good tool/timesaver for development)

2019-03-14 05:27 UTC, junderw commented
While I have permissions to merge this into Github, I don't have publish rights to npm.

Also, I am not familiar with this repository or how it works, and there are no tests... so it is hard for me to evaluate whether this PR is OK.

@dcousens any thoughts?

2019-03-14 05:28 UTC, chiguireitor commented
Aah yeah, npm is a deal breaker, as this goes into a lot of docker-compose stacks

2020-05-27 05:59 UTC, abunsen approved these changes
lgtm let's ship this puppy @dcousens

2020-05-27 07:54 UTC, merged

2020-05-27 07:54 UTC, junderw commented
Looks like I was made into publisher on npm.

2020-05-27 08:00 UTC, junderw commented
published as 0.9.1